### ISSUE TITLE
Write example queries

### ISSUE THREAD

**Issue by parseccentric** [gelic-idealab/komodo-data#4]
**What kind of task is this? Please use the appropriate label on the right**
- [x] New task -> `new task`
- [ ] Problem in the dev branch -> `dev branch`
- [ ] Problem in the main branch -> `main branch`

**Describe the new feature.**

Write some example queries on a captured data file. Print these queries to the console. Include comments explaining what the queries should do. If it's possible to include this as a test function or test file, do that so we can optionally run the queries when we need to but ignore them in production.

**Describe how to tell if it's implemented correctly.**

Manually inspect the data using MySQL workbench to see if your queries got only and all the data you wanted to.

**Comment by parseccentric** [comment]
@wallacerob -- this is definitely not my area of expertise, so please add or correct anything if you wish!

**Comment by parseccentric** [comment]
@wheeendiii Glad to hear you are almost done with this. What do you think of the description above? Is it feasible to conform your output to that description? 

If not, comment here, and we'll figure out a better way. 

If so, please commit the changes onto the `dev` branch and then do a `git push` to push them to GitHub. If you need help with the commit and push process, please let me know. Thanks!

**Comment by wheeendiii** [comment]
The description sounds great! I have included alternatives to test the output.  And yes, I will go ahead and push my example queries to  _dev_ branch.
